set autoindent
set tabstop=4
set shiftwidth=4
set relativenumber 
set number
set list
set listchars=eol:$,tab:>-,trail:~,extends:>,precedes:<

syntax on
colorscheme onedark

map <C-n> :NERDTreeToggle<CR>

let g:airline_theme='onedark'
execute pathogen#infect()

