export PATH=$HOME/bin:/usr/local/bin:$PATH
export ZSH_DISABLE_COMPFIX=true
export ZSH=~/.oh-my-zsh

ZSH_THEME="robbyrussell"

plugins=(
  git
)

KEYTIMEOUT=1

source ~/.oh-my-zsh/oh-my-zsh.sh

cd_ls(){
	cd $1
	ls
}
alias cd="cd_ls"
